### ISSUE TITLE
Change splatfest teams

### ISSUE THREAD

**Issue by iAroc** [Leanny/leanny.github.io#10]
Title explains is, changing the splatfest team in the middle of a splatfest would be nice

**Comment by Haxxie99** [comment]
step 1: save the save file before splatfest
step 2: when splatfest is going on ur team load ur backup file without a chosen team and choose the different one.

**Comment by Superx321** [comment]
which is not what i asked for. it would reset all the hidden stats, and even the front one like my current splatfest rank.

**Comment by SebiZocer** [comment]
I think this could be possible...

**Comment by Leanny** [comment]
I will take a look at this when the next splatfest begins. I wasn't able to do it this splatfest.
