### ISSUE TITLE
Virus Detected!

### ISSUE THREAD

**Issue by RCCRAFT1** [Leanny/leanny.github.io#102]
When I opened the .zip file, it said a virus was detected in the file, then I ran a scan on virustotal.com and found this, please fix this or take it down
![capture](https://user-images.githubusercontent.com/43323661/46642914-7a902000-cb2e-11e8-8a7b-c3e4a22f4b70.JPG)
![1](https://user-images.githubusercontent.com/43323661/46642917-7d8b1080-cb2e-11e8-955b-32ab4578bbf9.JPG)
![2](https://user-images.githubusercontent.com/43323661/46642918-7ebc3d80-cb2e-11e8-888a-813716567f46.JPG)

**Comment by Monotek18** [comment]
https://www.virustotal.com/en/file/f81b3e81db2819d0c489b27df59255ba1e6a52782563f767de27388000cc690b/analysis/1539247560/

0/59 -- where did you get the file you scanned?

**Comment by RCCRAFT1** [comment]
From the website

**Comment by RCCRAFT1** [comment]
and the file

**Comment by Monotek18** [comment]
false positive

**Comment by RCCRAFT1** [comment]
Its not a false positive, the thing gave me BOSD

**Comment by RRSlider** [comment]
Works just fine for me. Downloaded straight from the official website. 
I've gotten false positives on it when it was just released but it's always worked just fine. It's an issue with your AV, not the programme lmao.

**Comment by RCCRAFT1** [comment]
There is no official website, the thing is a Trojan

**Comment by Leanny** [comment]
Then don't use it, if you don't trust it. So far you are the only one with a BSOD...
