### ISSUE TITLE
Add missing gear and weapons.

### ISSUE THREAD

**Issue by 98otiss03** [Leanny/leanny.github.io#104]
- Missing Kensa Weapons included in 4.1.0

- Missing Splatoween gear

**Comment by Leanny** [comment]
![s1](https://user-images.githubusercontent.com/1884062/46972993-3f5a9780-d0c0-11e8-9618-97e7ef0bed79.png)
![s2](https://user-images.githubusercontent.com/1884062/46972994-3f5a9780-d0c0-11e8-9888-7c8db16b280e.png)
Both is already included.
