### ISSUE TITLE
Do we know how Group is determined for Splatfest Titles?

### ISSUE THREAD

**Issue by Vendily** [Leanny/leanny.github.io#105]
I was just wondering, as everything else is wonderfully explained, and it is completely understandable how all of the other categories are determined and activated, if we know how group is determined.
Do we not know yet, or is it random and there is no way to force a group?

I'm just curious.

**Comment by iSharingan** [comment]
it's based on clothing, species, gender, and weapon synergy. there are funny ways to abuse this, such as all 4 memebers wearing SR head gear AND SR footwear, along with the same weapon (for my example, Bloblobber). The result is ["The Salmon-Splattin' Salmon-Splattin' Bloblobbin' Crew"](https://twitter.com/NotGonnaCheck/status/1072703434170613760) (in the example we each had a different species/gender combo so none of that triggered)
