### ISSUE TITLE
Unhandled Exception: Index was outside the bounds of the array, Splatoon 2 V.4.3.0

### ISSUE THREAD

**Issue by ReggieBeverage** [Leanny/leanny.github.io#109]
I recently was able backup my Splatoon 2 save data. I believe I missed out on the Splatoon 2 World Championship In-Game Shirt, so I wanted to use this program to see if I couldn't add it in. I backed up my save after having just updating the game to 4.3.0, before having knowledge of this program. I went to open the save, and I keep getting an Unhandled Exception saying that the Index was outside the bounds of the array. I tried this with both the Checkpoint version of the save and the YallAreNuts version, only to get the same result. I assume that this is an issue with the program not supporting Version 4.3.0 yet, given how recent it is. I just thought I would make this issue known, to see if others may be having the same issue, and if it can possibly be fixed. Thank you.

**Comment by Leanny** [comment]
This means that the new Savegame version is not yet supported. We try to post an updated this week that will make SplatHeX compatible with it

**Comment by ReggieBeverage** [comment]
Cool! Thank you very much and I look forward to when it comes out!
