### ISSUE TITLE
Splatoon 2 4.3.1 Error when opening save - Invalid HMAC

### ISSUE THREAD

**Issue by Lopunny1** [Leanny/leanny.github.io#115]
When I open my saves with the latest version I get an error.
![capture](https://user-images.githubusercontent.com/46117665/50410089-c00ce100-0831-11e9-94c8-f2b4ff35af3e.PNG)

This is with a 4.3.1 Australian save using the newest Splathex. I've tried ripping the save in various programs and none work so I don't think its that.

Here is my most recent save.
[save.zip](https://github.com/Leanny/leanny.github.io/files/2707990/save.zip)

**Comment by Jonas9292** [comment]
It should work if you Reinstall SplatHeX and make a new Backup of your game than it should work fine.(for me it does but now the hole game is delited)

**Comment by Leanny** [comment]
4.3.1 changed the savegame encryption and it seems like there is a special case in save data that is not handled correctly (due to not enough testing data for me). I found the main issue and will try to release a fix later today (as I have a lot more test saves now)

**Comment by Lopunny1** [comment]
There also seems to be new ways for Nintendo to check saves as of 4.3.1. 
I've used this software for ages to do legitimate gear edits but have now been banned from using Splatoon online.

**Comment by lordofthereef** [comment]
Were you using an emunand? While I was using an emunand I was getting this error with dumps. After that I had not.

I had tons of issues editing the save, but eventually got it to work with only editing the ability chunks. Having read your ban warning though I have reverted to my "legit" save. Can you share what you were doing and how/when you got banned?

**Comment by Lopunny1** [comment]
No I hadn't been using emunand or anything like that. I'd boot my Switch into CFW and export my save, edit it and then inject it back into my switch, I'd then go back into stock firmware. 
All I had been doing is editing gear. All my gear was 'legitimate' in sense that it could all be obtained in game fairly.

To get my saves to work on this Splathex I needed to use an older save before 4.3. I reverted to that save, and then opened it up in splatoon so it did the cold blooded conversion stuff. Without going online I then managed to get that save to open in Splathex. I then edited that save with some gear edits, mostly giving gear main power up subs and chunk edits. I played lots of games with it yesterday and there were no problems.  

I just happened to start up the game today and it advised I wasn't able to use this software online on this console.It is only a software ban, I can't use splatoon online, everything else online like smash for example works fine. I haven't got any email from nintendo or anything yet.  Prior to this update I had been doing this for ages and ages and had no problems.

**Comment by lordofthereef** [comment]
Wow, that's a bummer. I just first tried any of this today. I didn't actually play any games online with it, just checked whether the changes took effect. I guess I will have to see... would be a damn shame if I got banned for an edit I didn't even use lol.

Sorry to hear of your ban by the way, but am thankful that you shared your experience.

**Comment by lordofthereef** [comment]
> So Lopunny when you reverted to older version savedata, is that mean you changed the online match amount? Or you did something wrong when you were reverting?

How can nintendo see your online match amount but not your gear data? Isn;t it all locally stored? Wouldn't checking any statistic be just as trivial as the next?

I always figured that people were getting away with these hacks not because nintendo had no way of checking, but because they simply werent actively checking. I could obviously be wrong.

**Comment by Lopunny1** [comment]
It could have very well been the online match amount. I checked my Splatoon phone app and saw there were a few games I must have played that I guess disappeared when I reverted saves. When I open these games in the app the data gets replaced with a different match that. I have never downgraded saves so this might have been the problem. Strange how it wouldn't have banned me straight away though.

I also had a hell of a lot of pure main power up gear, perhaps someone did report me? I am sure I have slipped up somewhere. But I did read that Nintendo supposedly upped the security of these saves so I thought I'd let everyone know.

**Comment by Road2Pirate** [comment]
Ok guys, let me explain, all the points lean lists on dangerous modifications are guaranteed a ban. **SO, be sure follow the instructions by lean to avoid a ban.**  And I know you guys want to change the main ability of gears. To some extent, it is a safe modification except some one report you use illegal gears. Therefore also be sure not using the gear never appears on mobile splatnet. You never know if some one made a list to record the gears once appeared. I have two websites that track the mobile shop gears.
https://gesotown.ink/list   and     https://www.ikaclo.jp/2/gears/   
So, when you are trying to edit the gear, plz be sure you have a look on these two sites first to ensure if  the main ability appeared on the gear. That will be helpful to reduce the change to be banned. 
Splatoon 2 is a P2P game, that means the splatoon online system only match players together, and it not monitor what is exactly happened in single match. So, that is the reason why some people change the weapon data and not be banned immediately. Then, when a single match end, the splatoon online system will receive the results to give you feedback but not check the gears' validity. So, that is the point, Nintendo will record any match you ever played, if the online match amount is wrong, that will guarantee a ban, same as MMR,  Level, Number of disconnects and Salmon run data.

**Comment by lordofthereef** [comment]
I understand what you mean, road. What I am saying is that if Nintendo is able to record the games you've played and compare them to your game save, how are we certain they not able to record anything else? 

My question is, do we KNOW that binge do has no means of collecting this data? I'm not talking assuming, since they haven't done it before. We assumed a lot of things for years with the 3ds, for example, and Nintendo changed things up. 

Again, I'm asking because I don't know. But it doesn't seem like an incredibly far fetched idea to think that binge do can take a look st saves that may be suspect. If they can check for "illegal" gear as well, I can't see why they couldn't compare other values.

**Comment by Leanny** [comment]
We are not sure what they are able to detect in 4.3.1. We discovered that they are able to detect various changes in the executable (they weren't able to detect this before). Maybe they also added savegame checks. We don't know for sure as they also obfuscated the code and it is really hard to reverse engineer it 100%

**Comment by Leanny** [comment]
After reading everything again it looks like its due to the old savegame. The game assumed that you 'savescummed' by having different values for various things (MMR for example) than the ones stored online. Since you cannot do this legit it flagged you.
Sorry to hear that this happened to you. We will try our best to understand the full de and encryption so this won't happen again

**Comment by Leanny** [comment]
This is hopefully fixed now
