### ISSUE TITLE
HMAC Error

### ISSUE THREAD

**Issue by M5201** [Leanny/leanny.github.io#118]
Recently updated Splathex and wanted to see if the editor can work. Now my save can't even be loaded into the software. I have a 4.3.1 save which worked before on Splathex v0.4.11. Not sure what is going on.

**Comment by M5201** [comment]
[save.zip](https://github.com/Leanny/leanny.github.io/files/2729019/save.zip)
Here is my save that I am trying to edit.

**Comment by DanyNHJD** [comment]
[save.zip](https://github.com/Leanny/leanny.github.io/files/2730028/save.zip)

getting the same error aswell, providing my save file.

**Comment by ZakkuZakku** [comment]
Checked!
Kudos @Leanny
