### ISSUE TITLE
Savegame not valid [Splatoon 2 Cartridge/No Updates/Firmware 3.0.0]

### ISSUE THREAD

**Issue by Darthsternie** [Leanny/leanny.github.io#12]
Hi,
First of I'm sorry if this Error is already known but I tried editing my Splatoon 2 Save today and for that purpose, I backed up the Save with both Checkpoint and YallAreNuts. Upon editing, SplatHeX Complained about the savegame not being valid though. I have Splatoon 2 as a cartridge, no Splatoon 2 Updates installed and am on Firmware 3.0.0 if this helps. I also attached my Splatoon 2 Savegame.
[save.zip](https://github.com/Leanny/leanny.github.io/files/2020238/save.zip)

**Comment by Leanny** [comment]
Right now we focus on compability to the latest version (savegame revision 3). Splatoon 2 1.0 uses savegame revision 0, which is not fully supported right now. We will add compability for older versions pretty soon

**Comment by Darthsternie** [comment]
Ah okay. Thanks for the Heads Up :)
I'll wait patiently then :)
