### ISSUE TITLE
Not so much an issue more so a question

### ISSUE THREAD

**Issue by Shawn12321** [Leanny/leanny.github.io#120]
The question in hand being is it possible to be banned for changing number of chunks. Can the anticheat detect weather or not the chunks have been hacked in or is that not possible?

**Comment by iSharingan** [comment]
there's potential for any edit to get you banned. Playing offline and getting chunks from an offline source (such as redeeming SR rewards offline or using the expanion's vending machine) can make it harder to detect, but it cant be guaranteed.
