### ISSUE TITLE
Hacking in specific gear

### ISSUE THREAD

**Issue by Agent-No-7** [Leanny/leanny.github.io#125]
How does one hack in specific gear? I have Splatoon 2 JP and was wondering how to get the dlc gear for my characters.

**Comment by Leanny** [comment]
By buying it. DLC gear has additional checks that prevent you from seeing them in your inventory without having them bought legally

**Comment by Agent-No-7** [comment]
Okay. Thank you for the response. That makes sense. I already have the spy
and emperor sets from magazines. I was hoping for the older stuff that
isn’t available.  Oh well.
