### ISSUE TITLE
Migrating data

### ISSUE THREAD

**Issue by Agent-No-7** [Leanny/leanny.github.io#128]
Is it possible to move/migrate/merge all clear data (story mode + octo) from one save to a fresh Rank (Level) 1 save?  If not, any suggestions?

**Comment by Leanny** [comment]
Bulk Edit -> extend the bottom window to make "Save Partition Tool" appear -> Mission -> Dump (this is story mode) -> Octo -> Dump (this is the DLC).
Then on the new savegame you do the same but restore the data instead. This will do a 1:1 copy of your old data into the new savegame.

AFAIK there are no ties to your user account in this part of your data, but it might always look strange when you have a fresh level 1 save with barely any playtime and a completed story/dlc, so be careful when using this feature
