### ISSUE TITLE
4.9.0 isn't functional - Is this the end?

### ISSUE THREAD

**Issue by Hypercubedoko** [Leanny/leanny.github.io#139]
As of update 4.9.0, splathex can no longer read the save data.  While you have stated that you may release hotfixes, this would probably be too big of an undertaking to consider. Are there any plans to add support for this new format, or is this simply the end for splat2 save editing?

**Comment by Leanny** [comment]
It still works though? There is no new save format and I just dumped my savegame. It shows me gear that was added in 4.9, so I guess it still works

**Comment by NKSquidNT** [comment]
hi Leanny i want to ask if you can make a little update because in4.9 it doesnt show every weapon. if it is only for me so than idk :(
