### ISSUE TITLE
WinRAR wont open splathex?

### ISSUE THREAD

**Issue by Shawn12321** [Leanny/leanny.github.io#14]
So i just downloaded the newest version of splathex and my computer continues to give me this error, ! Cannot execute "C:\Users\Jonathan\AppData\Local\Temp\Rar$EXa14964.21615\SplatHeX.exe" . I doubt that this is your guys fault in anyway but i was wondering if someone could help me out with this.

**Comment by Monotek18** [comment]
Try with 7zip instead.

**Comment by Shawn12321** [comment]
That worked thanks
