### ISSUE TITLE
Splat 3 gear database French translation abilities show drink name instead of ability name

### ISSUE THREAD

**Issue by thomasblanc** [Leanny/leanny.github.io#154]
Ticket title says it all, with the exception of sub power up and special power up, I can read drink name instead of ability name in "main ability" field for the gear database.

Needless to say severity is pretty low, but I wanted an occasion to say that what you're doing is incredibly appreciated by the community. Thank you so much!

**Comment by Leanny** [comment]
Thank you very much for the report and your words. The issue is fixed now
