### ISSUE TITLE
REEF-LUX 450 is missing name fields

### ISSUE THREAD

**Issue by Glazelf** [Leanny/leanny.github.io#156]
The REEF-LUX 450 is missing fields containing its name in the language files. It's [description](https://github.com/Leanny/leanny.github.io/blob/099ebc3261d22a377de7381d85a8b623abeea2e5/splat3/data/language/EUen.json#L1602) did get added.
I would add the name myself but I could only do this in romanic languages (by taking the name from the description, but I can't read Chinese and Japanese), so I felt like it was better to just make an issue.

A possibility is that the name isn't present in the 1.0.0 data but this seems unlikely since the description (containing the name) is present.

**Comment by Leanny** [comment]
This will be fixed on Monday, when I push the 1.1.0 data (the weapon description was in the testfire for whatever reason). As they contain some story spoilers, I want to wait with publishing a bit. 
For your bot I would like to ask you to add the names manually first:
```
Keyname: "StringerShort00"
CNzh: "LACT-450",
EUde: "LACT-450",
EUen: "REEF-LUX 450",
EUes: "AR-CR0 450",
EUfr: "Coralux 450",
EUit: "ARCO-RAL 450",
EUnl: "RIF-LEX 450",
EUru: "\u041a\u041e-\u0420\u0410\u041b\u041b 450",
JPja: "LACT-450",
KRko: "LACT-450",
TWzh: "LACT-450",
USen: "REEF-LUX 450",
USes: "AR-CR0 450",
USfr: "Coralux 450",
```

If you need certain data for testing purpose, feel free to contact me via discord (Lean#3146, discord ID 86905636402495488), then I can send you the files before Monday
