### ISSUE TITLE
 SplatHeX can support splatoon3?

### ISSUE THREAD

**Issue by still1987** [Leanny/leanny.github.io#157]
can SplatHeX support splatoon3?

**Comment by Leanny** [comment]
Hello. Splatoon 3 uses an online savegame for multiplayer related things and it is not possible to edit them. So splathex cannot support splatoon 3

**Comment by MeteorVE** [comment]
But it might still be a good choice if it can be remake into a read-only program that reads gear seed. 
Although we could still spend a lot of time tracking down the gear ...  :pepe_cry:

**Comment by DraconicNEO** [comment]
> Hello. Splatoon 3 uses an online savegame for multiplayer related things and it is not possible to edit them. So splathex cannot support splatoon 3

But I was able to get a modified save file from the Splatoon 3 modding Discord and the gear is unlocked and available for me in that save file. So it's definitely possible to do it.

**Comment by Leanny** [comment]
Are you connected online? Because the game keeps an offline cache (for stuff like the shoal), so modifying that is for sure possible, but not advised at all

**Comment by DraconicNEO** [comment]
> Are you connected online? Because the game keeps an offline cache (for stuff like the shoal), so modifying that is for sure possible, but not advised at all

Yes I've been blocking Nintendo Servers on my emuNAND (DNS.mitm and Incognito) since I got the switch so as to not get it banned. Why isn't it okay to modify the cache to add gear?

**Comment by Leanny** [comment]
If you are not connected to the online server, then everything is okay. If you are connected and can play online, the servers will detect a different savegame and try to sync it. Since they have history of the previous savegame, they will know that you modified it and flag your account. Right now all accounts are safe until the first banwave hits

**Comment by DraconicNEO** [comment]
> If you are not connected to the online server, then everything is okay. If you are connected and can play online, the servers will detect a different savegame and try to sync it. Since they have history of the previous savegame, they will know that you modified it and flag your account. Right now all accounts are safe until the first banwave hits

Ah I see, so it's fine unless I connect to their servers. That's good to know.
