### ISSUE TITLE
Dirty language values

### ISSUE THREAD

**Issue by Glazelf** [Leanny/leanny.github.io#159]
A bunch of language ([ex.](https://github.com/Leanny/leanny.github.io/blob/f36a4a6b8e884eba474e8e586a1c770c2f4a5673/splat3/data/language/EUen.json#L3843)) text entries have extra bracketed group numbers in the value string now, this wasn't the case before 1.1.0.
I assume this is a mistake haha

**Comment by Leanny** [comment]
This is not a mistake, this is used for formatting, i.e. this key is used for every salmon run boss in the game and the group tells me where to insert the name
```
"CoopBossKillNum_Lv00": "[group=0004 type=0007 params=00 00 00 00] Splats x 10",
```

**Comment by Glazelf** [comment]
I personally don't feel like this should be included with the value in the same string, especially since it's sometimes before the string and sometimes after.
