### ISSUE TITLE
[Feature Request] Gear Seed Recovery localstorage

### ISSUE THREAD

**Issue by Zhongren233** [Leanny/leanny.github.io#166]
When close the tab page will lost all filled data
Could we use localstorage to save data?

**Comment by Leanny** [comment]
It already uses local storage (can easily be checked in dev tools). Can you give some more context in what you did?

**Comment by Zhongren233** [comment]
> It already uses local storage (can easily be checked in dev tools). Can you give some more context in what you did?

Sorry,i have never open Gear Database tab.

In fact,I always use Gear Seed Recovery tab and every open I must refill previous data.

Thanks you to tell me this.

**Comment by Zhongren233** [comment]
![image](https://user-images.githubusercontent.com/62706664/194806545-c7f1a2b6-870c-4406-9fa5-baffd542e4e3.png)
so this div is hidden when gear database is not empty?
I think it is better display this div all the time.

**Comment by Leanny** [comment]
Div is now displayed all the time
