### ISSUE TITLE
Search target ability sequence

### ISSUE THREAD

**Issue by zark314** [Leanny/leanny.github.io#167]
Could you add a target ability sequence search function,
 I made a program myself based on your seed calculator and Technical Details ,it used to search all possible future situations to find target ability sequences,
but I am not a computer major and have not learned JavaScript  , although a simple html version is made（in my GitHub , https://zark314.github.io/）,
but the functionality is very weak, so I would like to ask you to do such a function, I would like to make a Chinese version for your website.
Thinks for your contribution.

**Comment by Leanny** [comment]
Thank you for the suggestion! I will add a search function in one of the next updates!
