### ISSUE TITLE
Error 0x800700E1 when attempting to extract file

### ISSUE THREAD

**Issue by SunTheCourier** [Leanny/leanny.github.io#17]
Windows File explorer returns Error 0x800700E1 when attempting to extract program. (caused by Windows Defender???) 

![image](https://user-images.githubusercontent.com/22406854/40337061-28b31064-5d22-11e8-9aad-22cdabf0d08f.png)

**Comment by WemI0** [comment]
False positive, you can add an exception

**Comment by Leanny** [comment]
Current report: https://www.virustotal.com/#/file/5fe8f629764435323c5156288178a8fb7f957ff21cba2f24eab105d2beeb20dc/detection

It is a false positive for the 2 AVs.

How to Fix / solution: Turn off real-time protection in Windows Defender. Disable Antivirus protection.
