### ISSUE TITLE
Question ( Can we use the seed algorithm to reversely infer Lottery Rewards?

### ISSUE THREAD

**Issue by LiuJiLan** [Leanny/leanny.github.io#170]
If we can reversely infer the seed by the order in which the slots of gears will appear. Then can we reversely infer the seed of the lottery by recording the results of the recent lottery? Then use this seed to figure out how many times I have to draw to get that 0.1% Banner?
I am very curious about this question. I would be grateful if you had time to answer my questions.

**Comment by Leanny** [comment]
Unfortunately this is not possible. Gear seeds are 32 bit, which can easily be bruteforced by any phone nowadays. Most of the seeds used in the (including lottery) use a 128 bit seed (http://bugcharmer.blogspot.com/2012/06/how-big-is-2128.html), which is not possible to bruteforce with current technology. Also a second difference is that for gear ability we have exact numbers, while for the lottery we only have a range (like every number between 0 and 0.1 results in the banner), so it would require a lot more data to even get somewhere close

**Comment by LiuJiLan** [comment]
I see. What's a pity news, it seems that I still have to go to the draw once a day to try my luck. 
Thank you very much for answering my questions.
