### ISSUE TITLE
Questions about getting data from SplaNet

### ISSUE THREAD

**Issue by Sichongzou** [Leanny/leanny.github.io#177]
Hello, author. I know that it is now allowed to obtain my JSON data from SplaNet, and it only takes 3-4 skills to determine a seed with the data obtained through this method. But I want to ask if I buy a new dress in Splatoon3. In this case, if I want a new dress seed, I need to find the bot again to get my JSON according to the normal operation, but what should I do with the skill data and seed on my original dress, or I directly add a piece of equipment on the page, but I'm not sure whether this method can let me get the seed directly. After all, nobody wants to paint 9-10 skills to get the seed. ha-ha

**Comment by Leanny** [comment]
Hello, you only need to do it once. After that you can add the gear manually and it will still work faster

**Comment by Sichongzou** [comment]
OK. So after I import it once, there will be new clothes. I just need to add new clothes, and then I can check new clothes to quickly find seeds. Is that right?

**Comment by Leanny** [comment]
Yes

**Comment by Sichongzou** [comment]
OK, thank you for answering my questions. If I have other questions, I will submit new issues. Thank you very much for your time and effort on this project 
![UU~2)MCOM$I4OJ1SWX2J3XR](https://user-images.githubusercontent.com/68594934/202325160-894cbcbd-5cef-46df-99cd-9582fae090e9.jpg)
