### ISSUE TITLE
Mobile web interface adaptation

### ISSUE THREAD

**Issue by Sichongzou** [Leanny/leanny.github.io#183]
Hello, author. Would you consider providing mobile phone support for web pages. Although the interface of the project running on the mobile phone is perfect, some pages are still not well adapted. For example, the interface of my clothing warehouse works like this on my Android phone
![Screenshot_2022-11-21-09-07-17-642_com android ch](https://user-images.githubusercontent.com/68594934/202938095-5626af39-9537-42cf-b72c-04a936721eba.jpg)

**Comment by Leanny** [comment]
Unfortunately I do not have many experience in developing webpages for phones. But I try my best to improve it for the next update

**Comment by Sichongzou** [comment]
Thank you. Please do your best. Thank you very much for your time and effort on this project
![UU~2)MCOM$I4OJ1SWX2J3XR](https://user-images.githubusercontent.com/68594934/203185329-2b9ba3fc-d605-42a1-bb42-21119f1377e1.jpg)

**Comment by spacemeowx2** [comment]
This may be off-topic, but as I understand it, there are some limitations to using localStorage on iOS/iPadOS. I think it's important to inform users on mobile to avoid unnecessary problems (such as unintended data loss)

https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

**Comment by Leanny** [comment]
Thanks for letting me now that iOS is making things worse again. I will most likely add a note in a future update

**Comment by Leanny** [comment]
I pushed a new version with improved mobile design for the gear database. Please let me know if this makes it better for you and if you have more requests

**Comment by Sichongzou** [comment]
Ohh A new page! I like it. It allows me to quickly find my equipment on the mobile terminal. It's great on my phone! But there seems to be a problem with search.

**Comment by Sichongzou** [comment]
Sorry, it seems that my mobile phone doesn't allow me to upload pictures. Please wait for me to use the computer

**Comment by Sichongzou** [comment]
![Screenshot_2022-11-27-20-15-28-572_com MyFusApp S](https://user-images.githubusercontent.com/68594934/204135003-4d7612b5-f8d3-4ec8-8b7c-9f8115b076aa.jpg)
![Screenshot_2022-11-27-20-15-32-942_com MyFusApp S](https://user-images.githubusercontent.com/68594934/204135023-72421c5e-7a16-4b1f-bc83-10d152f9c24d.jpg)

**Comment by Leanny** [comment]
Ah, it seems like the text is too long for some languages. I will make adjustments, thank you

**Comment by Leanny** [comment]
I pushed another update that might fix the issue. Can you please provide some feedback again?

**Comment by Sichongzou** [comment]
Emmm This is the page I displayed on my Android device
![Screenshot_2022-11-28-08-22-45-614_com MyFusApp S](https://user-images.githubusercontent.com/68594934/204168097-87059c63-8995-4673-9382-01a2478ff625.jpg)

**Comment by Sichongzou** [comment]
Wow, it works perfectly on my mobile phone at present. Thank you for adapting to this problem. If I have new questions or ideas, I will submit new issues.
![UU~2)MCOM$I4OJ1SWX2J3XR](https://user-images.githubusercontent.com/68594934/204408449-fd79734e-6266-46d5-8155-2a42d068ffbf.jpg)


![Screenshot_2022-11-29-08-20-03-482_com MyFusApp S](https://user-images.githubusercontent.com/68594934/204408487-70d64393-7df0-42d9-8a95-ff41bfcdb031.jpg)
