### ISSUE TITLE
Splatoon 3 - Seed Listing - Shell-Out Machine is not saving updated seeds

### ISSUE THREAD

**Issue by LRFLEW** [Leanny/leanny.github.io#184]
When I update the seed in the Shell-Out Machine predictor, either by typing in a new seed into the input or clicking one of the "Update Seed" buttons, the updated seed doesn't get preserved if I switch tabs or refresh the page. This is particularly annoying, since the "current seed" updates every time I use the Shell-Out Machine, and the app is stuck defaulting to an old seed (maybe the first seed it discovered?)

For reference: I'm using Firefox 107.0 (64-bit) on Windows 10 22H2. I also have a number of browser extensions installed, but none that *should* be messing with local storage. If you can't replicate the issue, I can try going through my extensions to see if I can identify one as the cause.

Looking through the currently open issues, this *could* be related to #179, but the issues occurs without switching tabs, so the description of that issues doesn't sound like it applies here.

**Comment by Leanny** [comment]
Please use the other button instead (Update Seed and Save Gear). The button is wrongly localised and should be "Update and Save Seed" instead, but the functionality is what you are asking for
