### ISSUE TITLE
[SP3-Seed List] [Bug] Salmon Run Type Miscount

### ISSUE THREAD

**Issue by qjzcj2008** [Leanny/leanny.github.io#193]
It seems now all Salmon Run are miscounted as big run in Seed List SR Reward Prediction Function. No matter what date I choose, the slot number all set as 24 by default. And calculated as big run, makes the result don't match what I got from actul game play.

Here is what I got from the SR Reward Prediction Function. And it even says the rewards can still be money after 1200p, so I think it may be miscounted as big run rather than a nomarl SR.
![image](https://user-images.githubusercontent.com/16514953/207010758-e03dbfdb-9a3d-4866-b637-a639509e3c59.png)

And here is what I got in actul game play.
![image](https://user-images.githubusercontent.com/16514953/207010909-010103c8-821b-4a93-a6c5-b0f5a454a168.png)

And this is the what Bonus Meter after 1200p looks like in game.
![image](https://user-images.githubusercontent.com/16514953/207011560-e19e8348-f098-408c-9bc2-d51784beef86.png)

If you need more infomation about this, plz feel free to ask me provide what you need.😊

**Comment by RayPS** [comment]
Got the same issue earlier today, I can confirm it's fixed now.

**Comment by qjzcj2008** [comment]
THX! Just rechecked the prediction, it matchs game now!👍 I think it's fixed now.
