### ISSUE TITLE
Brand New Gear checkbox is missing

### ISSUE THREAD

**Issue by liyiz** [Leanny/leanny.github.io#198]
Hello, the checkbox to check the seed for a brand new piece of gear is missing. It was working a few days ago, but it no longer appears anymore when you're looking up gear. Here's a screenshot of the problem
![Screenshot 2023-02-19 000338](https://user-images.githubusercontent.com/5160472/219905010-b29a9b24-7460-42be-af1a-ff1fbc4aaae3.png)

**Comment by Leanny** [comment]
Please make sure you have a gear key set. Easiest way to do this is by using a replay code

**Comment by liyiz** [comment]
Thank you, that was the missing bit - I uploaded a replay code and the checkbox appears now.

![Screenshot 2023-02-19 093108](https://user-images.githubusercontent.com/5160472/219940043-f622d773-a94e-4839-a631-c55b0826739a.png)
