### ISSUE TITLE
Custom Splattershot Jr, Sloshing Machine, Heavy Splatling Deco and Rapid Blaster Pro are still on the "Future Weapons" list

### ISSUE THREAD

**Issue by MarioKart7z** [Leanny/leanny.github.io#2]
All the weapons listed in the title are now obtainable in-game

**Comment by pswiifanwmi** [comment]
As is the Bamboozler 14 Mk 1.  Also, the values are wrong now, and the Tenta Brella is missing entirely.  Though interestingly, the Juice Parka is in the list as a current clothing item.

**Comment by Leanny** [comment]
I will not update the list until I am able to further datamine the data since the whole page is created automatically. I dont know when I will be able to do it again.
