### ISSUE TITLE
It says that the titles doesnt match up, but they do? help

### ISSUE THREAD

**Issue by kyregcy** [Leanny/leanny.github.io#202]
Before we start, im from latinomerica so thats why the screenshots from both the page and the switch are in spanish, i will translate if its necessary
![Screenshot_20230519_153713_Kiwi Browser](https://github.com/Leanny/leanny.github.io/assets/111604572/30da1585-bdc9-40ed-a565-9da831574ee9)
I want to get the title seed, but as seen in the sc, it says that "the titles doesnt match up" and it says "to have all titles listed in my profile", which i guess are the titles from the game but located manually in my profile
I have proof that both of these are the same titles 
![Screenshot_20230519_153755_Kiwi Browser](https://github.com/Leanny/leanny.github.io/assets/111604572/922f256d-95b4-4cd8-a517-a3d97243069a)
![2023051915391700-4CE9651EE88A979D41F24CE8D6EA1C23](https://github.com/Leanny/leanny.github.io/assets/111604572/bcdd300c-d6d8-48dc-8b7c-15598edd1621)
I will not translate since from the words alone you can tell that these are the same without the meaning mattering, so what i understand here at least that the game's titles have to be the same titles from this page profile, so idk what im doing wrong, help?
(Oh yeah and also heres my general level and my catalogue level, if thats the problem of course but as seen in the first sc of here i put level 10 of the catalogue)
![2023051916194400-4CE9651EE88A979D41F24CE8D6EA1C23](https://github.com/Leanny/leanny.github.io/assets/111604572/426871a8-3c8a-4a78-ac73-107042e388a2)
![2023051916194600-4CE9651EE88A979D41F24CE8D6EA1C23](https://github.com/Leanny/leanny.github.io/assets/111604572/eb4c7718-d747-4ee4-b515-47029aeac12c)

**Comment by Leanny** [comment]
Thank you for the report. Next time please report them in the [seedchecker repository](https://github.com/Leanny/splat3seedchecker/issues).
The issue seems to be that you only have 1 title from an external source (i.e. gacha machine) and the checker assumes that you need at least 2 titles. I deployed a fix, please let me know if it works for you now

**Comment by kyregcy** [comment]
YEAAAA, it works now, thx! and also sorry for that i will make sure that next time is gonna be in the repository :D
