### ISSUE TITLE
Import Export Slots and Drinks for Geer Seed Recovery

### ISSUE THREAD

**Issue by chenyenru** [Leanny/leanny.github.io#204]
<img width="1280" alt="image" src="https://github.com/Leanny/leanny.github.io/assets/42967019/34a98b36-a98d-4c0d-a277-25b718312da6">

Suggestions:
- It would help a lot if we could save the slots for gear locally (maybe through indexedDB? Or by exporting and importing data as json) so that we won't have to reenter the slots and drinks value every time before we get 12 slots.
Thank you!

**Comment by Leanny** [comment]
Gear database > create your gear
Then you can also save them

**Comment by chenyenru** [comment]
Ah my bad, thank you!
