### ISSUE TITLE
Why octoling hack dont work

### ISSUE THREAD

**Issue by Alphaggedon** [Leanny/leanny.github.io#23]
why the octoling hack of splathex 3.0.1 dont works??

**Comment by Haxxie99** [comment]
because you must unlock it(description)

**Comment by Alphaggedon** [comment]
how i can unlock it?

**Comment by Haxxie99** [comment]
U get an octo expansion, wait the release and then can complete 80 levels and get the octolings. You can get em after that in modify player in game. And then the octolings are in splathex.
