### ISSUE TITLE
weapon freshness / victories

### ISSUE THREAD

**Issue by iwashii** [Leanny/leanny.github.io#28]
Could it be possible to edit those?

**Comment by Leanny** [comment]
In the works.

**Comment by Leanny** [comment]
We added a freshness viewer for now. When I figured out how to change them without breaking anything, it will be added as well. I could not find anything related to victories in the savefile though, so this might not be possible

**Comment by iSharingan** [comment]
victories aren't going to be there. Freshness is cumulative and not tracked by win/loss ratio. Also a loss at 20 removes more 'freshness' than a loss at 5, etc.
