### ISSUE TITLE
SplatHax: Save transfer to another account?

### ISSUE THREAD

**Issue by x43x61x69** [Leanny/leanny.github.io#3]
I tested and find that it's possible to dump and re-inject Splatoon 2 saves between consoles/regions (e.g. EU saves to US game) for the same account. However, when trying to inject the save of User1 to User2, regarding the same or different consoles, it seems that User2 will have the same online profile as the donator account, result in error when going into the lobby. (Says this isn't available in this region or something.) So I assume some sort of online ID was stored in the save, tho they encrypted the save now so I can't really dig into it.

If that's the case, is there a way to scrub the online info off and that save so it can be reused? As it would be much easier than doing all the stuff again just to create another profile with the same settings/gears etc. Also do you know if they keep records on the sever regarding user levels/coins? (aka is player editing safe afawk?)

(I know SplatHax is not open source, but I think you can consider open a repo just for the issue tracker.)

**Comment by Leanny** [comment]
It should be possible, we will take a deeper look at it

**Comment by x43x61x69** [comment]
Thanks!

**Comment by x43x61x69** [comment]
Sorry but I found that the error was due to its region setting, not the save itself. It worked after I changed the user region. Thanks again!
