### ISSUE TITLE
Salmon Run Editor Not Working

### ISSUE THREAD

**Issue by trashpack** [Leanny/leanny.github.io#31]
When I click save it won't close the window and whenever I log in after changing my stats to be a profreshional, it always puts me back where I started, which is part-timer.

**Comment by Leanny** [comment]
Under investigation

**Comment by Leanny** [comment]
This might be fixed now, please report back.

**Comment by trashpack** [comment]
It still is not working. But good job with the freshness viewer.

**Comment by Leanny** [comment]
I figured out whats wrong and tested it as well. It will be fixed in the next version!

**Comment by trashpack** [comment]
Ok thanks! 😃
