### ISSUE TITLE
i dont have the octoling option and i have the dlc and i finish the story mode

### ISSUE THREAD

**Issue by TheReborne** [Leanny/leanny.github.io#37]
![capture png3](https://user-images.githubusercontent.com/39713270/40630640-8fd576fa-62aa-11e8-8630-183be41c88b4.PNG)

see i only have female and male

**Comment by Haxxie99** [comment]
The reborne wait for expansion. I am trying to ask them and even donate them for implementing a way to get an octoling before completing expansion but still nothing works.

**Comment by Haxxie99** [comment]
For splathex not to crash after seeing ur player is an pvtoling
