### ISSUE TITLE
[Request] Add splatfest tees to the gear editor

### ISSUE THREAD

**Issue by ParkerSaint** [Leanny/leanny.github.io#40]
Seeing as this is not yet a feature, I think it would be useful to add this in.

**Comment by Haxxie99** [comment]
They are already there

**Comment by Haxxie99** [comment]
Double check

**Comment by ParkerSaint** [comment]
I'm still not seeing them... strange

**Comment by Leanny** [comment]
"Tees"? The previous ones?

**Comment by ParkerSaint** [comment]
Yes, if that is possible.

**Comment by iSharingan** [comment]
there is only one splatfest tee. the design is set by extra data and the both the shirt and the texture applied to the shirt are removed when the splatfest ends.

**Comment by ParkerSaint** [comment]
Okay, that's what I thought, thanks for the response.
