### ISSUE TITLE
Some Questions About Rank Hack

### ISSUE THREAD

**Issue by SeijiTakara** [Leanny/leanny.github.io#41]
Hello 
Your SplatHex is amazing andd really helps me to discover the world of splatoon2,
and I have some questions which I am curious of the feature of this app.
1. Are you prepare to doing the function which can control the crack of the Rank Bar or modify the Rank?
2. Is it possible to Run this hex in Nintendo Switch in the future, like PokeHex in 3DS?
3. Can I watch how many win my weapon get? in the future?

**Comment by Shawn12321** [comment]
If you were to modify your rank, your MMR would be way off. This would cause you to get banned effective immediately. Nintendo added in the MMR to make sure that people without the skill couldn't hack their way up.
