### ISSUE TITLE
Octoling Tab

### ISSUE THREAD

**Issue by FishiLEG** [Leanny/leanny.github.io#43]
The octoling tab wont
![image](https://user-images.githubusercontent.com/39755777/40700527-c36f168a-638e-11e8-9448-430b87d552d8.png)
 appear and I bought the dlc how do I get them?

**Comment by 98otiss03** [comment]
can you read

**Comment by Haxxie99** [comment]
https://drive.google.com/file/d/1amWtqgDuFcrfGPOJyGTtXz7QwP7fnCLE/view Tutorial do before it’s closed

**Comment by FishiLEG** [comment]
I used it and it works yess

**Comment by Haxxie99** [comment]
Ok

**Comment by Joseph2404** [comment]
how do i tell the version?

**Comment by FishiLEG** [comment]
So i have all versions downloaded byt 3.0 did it for me version 4 wont
allow it. It was fixed with the update

**Comment by Joseph2404** [comment]
It's not working with my versions.

**Comment by FishiLEG** [comment]
Yah they patched it you have to have version 3.0 to work

**Comment by FishiLEG** [comment]
Doesnt have plaza photo editor

**Comment by Joseph2404** [comment]
No

**Comment by FishiLEG** [comment]
Lel

**Comment by Joseph2404** [comment]
any idea on what to do?

**Comment by FishiLEG** [comment]
Already did it

**Comment by Joseph2404** [comment]
[SplatHeX.zip](https://github.com/Leanny/leanny.github.io/files/2055891/SplatHeX.zip)
This is my version

**Comment by FishiLEG** [comment]
Does it show plaza image edit?

**Comment by Joseph2404** [comment]
where is that located?

**Comment by FishiLEG** [comment]
Player edit

**Comment by Joseph2404** [comment]
no it does not exist

**Comment by FishiLEG** [comment]
Is samoln run edit working

**Comment by Joseph2404** [comment]
Yes

**Comment by Joseph2404** [comment]
if you have 3.0.0 you can drop the zip file in the comment box.

**Comment by FishiLEG** [comment]
Not right version

**Comment by FishiLEG** [comment]
Cant share files

**Comment by Joseph2404** [comment]
Oh okay, I was just wondering if I had it well anyone ways thanks for the help bye.

**Comment by FishiLEG** [comment]
You will have to pm in discord to get it i dont wamt to give away the
secrets

**Comment by Joseph2404** [comment]
Joseph#4610

**Comment by Haxxie99** [comment]
Use 3.1 or 4.0
