### ISSUE TITLE
Guys octohax until it’s deleted v4.0

### ISSUE THREAD

**Issue by Haxxie99** [Leanny/leanny.github.io#45]

**Comment by Haxxie99** [comment]
Use before it’s deleted

**Comment by Haxxie99** [comment]
V4.0 splathex and cheat engine

**Comment by Joseph2404** [comment]
Could i have a download link for 4.0 or 3.1?

**Comment by 98otiss03** [comment]
lol you used the video i posted on google drive

**Comment by Haxxie99** [comment]
I leaked it to a lot of people 98otiss03

**Comment by Monotek18** [comment]
"leaked" kek, it was in the code of splathex, which mean they don't care about it being public.

And the latest update killed hekate 😂
