### ISSUE TITLE
Add Off the Hook amiibo gear

### ISSUE THREAD

**Issue by 98otiss03** [Leanny/leanny.github.io#47]
Apparently, someone got Off the Hook amiibo gear. Can you add these to SplatHex?
![image](https://user-images.githubusercontent.com/38541316/40809988-c488e6e8-6502-11e8-87b8-b99149ab109f.png)
![image](https://user-images.githubusercontent.com/38541316/40809995-cac2a7ce-6502-11e8-9312-d33f7582a016.png)
![image](https://user-images.githubusercontent.com/38541316/40810003-cf594950-6502-11e8-875b-78505e2b9c22.png)
![image](https://user-images.githubusercontent.com/38541316/40810009-d4fe9b76-6502-11e8-9a75-f3e3bd74280c.png)

**Comment by Leanny** [comment]
They are not obtainable with savegame editing, they need additional editing outside of the savegame to work. They will be added when they are available via savegame editing
