### ISSUE TITLE
unlock shoal map problem

### ISSUE THREAD

**Issue by miyokosigma** [Leanny/leanny.github.io#50]
unlock all stages for The Shoal will cause regular stage doesn't show in menu because salmon run stage will take it's place and there is just 23 space for the map.salmon run stage also will be unlock in "take a photo with amiibo"menu and will make the game crush.
suggest a menu to delete unnecessary stage.

**Comment by 98otiss03** [comment]
I have the same problem, I can't access wahoo world in the shoal, because i have the salmon run maps

**Comment by Leanny** [comment]
We will add a button for this
