### ISSUE TITLE
Salmon Run gears (Grizz co.) editing

### ISSUE THREAD

**Issue by puni-puni** [Leanny/leanny.github.io#52]
I was unable to edit the main ability of Grizz co. brand gears ... was it intentional?
Before the last few update to Splathex I was certain I could change them.

It helped me when I was unlucky farming for specific main ability on the gear rewards.
Thank you for your hard work!

**Comment by InkxtheSquid** [comment]
I was unable to edit to, I want this to be a thing so I can have a rsu Cap of Legend

**Comment by Leanny** [comment]
This will be fixed in the next release (probably this week)

**Comment by puni-puni** [comment]
With all the embodiment of this word: Booyah!
