### ISSUE TITLE
expenrience edit

### ISSUE THREAD

**Issue by miyokosigma** [Leanny/leanny.github.io#53]
I noticed that gear expenrience edit doesn't work at all.It won't show the true exp when view gears.Is that my fault when backup my save or it just don't have this function?

**Comment by iSharingan** [comment]
editing the exp on gear is irrelevant when you can just set the next/previous/max level as you want. the numerical value is broken, yes, but that doesn't mean you need it

**Comment by Leanny** [comment]
This is indeed a bug as I just found out... under investigation

**Comment by miyokosigma** [comment]
> editing the exp on gear is irrelevant when you can just set the next/previous/max level as you want. the numerical value is broken, yes, but that doesn't mean you need it

just a report about something might not work.It doesn't matter whether I need it or not.[smile]

>
