### ISSUE TITLE
Octo Expansion editor

### ISSUE THREAD

**Issue by 98otiss03** [Leanny/leanny.github.io#54]
A new tab for editing stages, flags, mem cakes and amount of mem medals and CQ points.
also add the new expansion gear.

**Comment by SebiZocer** [comment]
i think hes already working on it. I hope that we can chance the main-attributes of the octo-gears.

**Comment by 98otiss03** [comment]
Editing the main ability is a bad idea, you are more likely to get banned, unless it was on SplatNet2.
[I have already 100% OE so I don't need this badly.]
