### ISSUE TITLE
possibility of importing/exporting a decrypted version of the save?

### ISSUE THREAD

**Issue by iSharingan** [Leanny/leanny.github.io#56]
Simply requesting a raw import/export of the decrypted save for tinkering purposes. If implemented, it would need to be locked behind some sort of 'secret' (such as clicking the version number X amount of times) to prevent people with no clue what they're doing from accidentally breaking their save (or as separate tool) - but for those like myself, the ability to more readily test values/offsets a bit can help provide offsets/values/etc. that much quicker, should anything of use be found.

I understand this could bypass some things, like the locked ranked editing, so I'm not entirely expecting a yes, but finding and editing such data successfully in a raw, unencypted save is still beyond the capabilities of most who try to abuse it.

**Comment by 98otiss03** [comment]
Nintendo made it you have to make sure your MMR matches your rank to rank up, so if the MMR is incorrect then it might ban you.

**Comment by iSharingan** [comment]
Actually the mmr controls rank skips. I intentionally played poorly on an alt and got 1600-ish mmr in S+0 without any edits. Playing poorly then ranking down may cause several rank losses, whereas a mmr of 1700+ when ranking up from C- will send you to B- or higher

**Comment by WemI0** [comment]
You can do that now:
https://gist.github.com/SciresM/dba70bc2ee7eca11e1bd777ecb58ff16

Feel free to share offsets we might not already have

**Comment by iSharingan** [comment]
is there a specific syntax for decrypting the save with the script? the closest I get is `python nisasyst.py save.dat Message/save.dat`
which results in the "Input appears not to be an encrypted Splatoon 2 archive!" error

**Comment by Leanny** [comment]
If you just want to decrypt the savegame, you can drag and drop it into the latest splathex version. Then open it with a hex editor to see the decrypted content. There is no confirmation for a successful de/encryption right now, so just check the file in a hex editor
