### ISSUE TITLE
Bulk Edit didnt gave me Octogears

### ISSUE THREAD

**Issue by SebiZocer** [Leanny/leanny.github.io#58]
Hi,
i started Splatoon 2 with a new user and the bulk edit dindt gave me the octo gears. I have the Octo-DLC buyed legal. I didnt checked the dlc out with the new user. Should i start the octo-dlc and try it again?

**Comment by iSharingan** [comment]
the octo DLC gear doesn't appear in the editor, as it hasn't been updated since release

**Comment by Leanny** [comment]
With the recent release we decided that "special gear" should only be editable and not addible to ensure your savegame stays valid and it's less probable for you to get banned
