### ISSUE TITLE
Ideas for hacks

### ISSUE THREAD

**Issue by Alphaggedon** [Leanny/leanny.github.io#6]
**Weapon Maker**
Can you do a weapon maker in splatHex? I mean, can u make an editor in which you can edit the special,subs or the skin of a weapon? for example, change the color of the dapple dualies to purple or black

**Change the color of Ink**
like the hacks of splatoon 1,change the color to red,black,white or a colour of some splatfest

**Salmon run weapons**
export the salmon run weapons in the program to use with the hacks

I really have no idea how to hack but I think that with your abilities you could do some of these things

**Comment by SebiZocer** [comment]
Please note, that he can only edit playerdatas. Changing the color of weapons, armor or ink needs a real hack for Splatoon2 and cant be done with editing playerdatas

**Comment by Monotek18** [comment]
you can't do that with a save editor, but it should be easy to do with ram editing or romfs patching.

**Comment by Monotek18** [comment]
"Could you tell me how it's done? that is to say, I am sure that only a person with a certain level of hacking can do it but for trying"

Not as hard as you think, but as I said we can't because we don't have the tools.

**Comment by Alphaggedon** [comment]
Well, I guess I'll wait for the security of the switch to be reduced and hacks to be made in a wider range, until then I'll keep watching what you do and giving you all my support uwu
________________________________
De: Monotek18 <notifications@github.com>
Enviado: jueves, 17 de mayo de 2018 6:31
Para: Leanny/leanny.github.io
Cc: Alphaggedon; Author
Asunto: Re: [Leanny/leanny.github.io] Ideas for hacks (#6)


"Could you tell me how it's done? that is to say, I am sure that only a person with a certain level of hacking can do it but for trying"

Not as hard as you think, but as I said we can't because we don't have the tools.

**Comment by Leanny** [comment]
We cannot do anything that is affected in game. Basically we can only do things that can change between turning off your console and turning it on again.
