### ISSUE TITLE
Japanese Exclusive Gear

### ISSUE THREAD

**Issue by LukeArts** [Leanny/leanny.github.io#64]
Is there a way to add the ability to actually add the Japanese exclusive gear to our files? Right now when you add it, it won’t appear in the game.

**Comment by 98otiss03** [comment]
It appears, you have to wear the gear otherwise it will disappear.

**Comment by LukeArts** [comment]
I wore the gear and it just changed it to the default clothes when you first start the game. Unless I did something wrong.

**Comment by Onebranchyboi** [comment]
The gear doesn't even show up to begin with on mine

**Comment by Leanny** [comment]
Early versions of splathex supported it but it lead to bans for illegal gear. So we decided that most special gear is only editable when you obtain it legally in the game. If you really want to have the gear, download one of the older versions of splathex
