### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Rainbakku** [Leanny/leanny.github.io#7]
Opening the player editor gives me an ArgumentOutOfRangeException because value exceeds the "Maximum"

**Comment by Leanny** [comment]
Please provide the savedata to me via Discord (Lean#3146) or twitter DM, so I can use it to debug.

**Comment by iwashii** [comment]
This happened to me as well after setting the star meter to 10 and then going to reset so it became 11
