### ISSUE TITLE
Add in hidden gear?

### ISSUE THREAD

**Issue by EnriUnagi** [Leanny/leanny.github.io#71]
Add the option to add in the hidden gear that don't have proper names. Such as Salmon Run cap, Agent 3's Tartar Headset, etc.

**Comment by 98otiss03** [comment]
This isn't possible without forcing gear to be worn, also in order to keep the hidden gear, you need a file modification.

**Comment by Leanny** [comment]
Most have additional checks that are not possible to bypass with savegame editing alone
