### ISSUE TITLE
[Question] How to properly change xp/level

### ISSUE THREAD

**Issue by Kascade0** [Leanny/leanny.github.io#72]
Can changing your level (say 20-30) be detected? 
Would I be better off adding crusty sean xp boosters to be safe?

**Comment by n0drak** [comment]
If I were you I would play until reaching the XP intended . Playing with XP can be detected so is a banned alarm.

**Comment by Kascade0** [comment]
So modifying the Crust Sean xp boosters and using them may result in a detection and/or ban?

**Comment by Leanny** [comment]
You don't. The safest way is to go with EXP tickets

**Comment by Kascade0** [comment]
Sorry for the misunderstanding. But that was what I meant. I appreciate the reply.
