### ISSUE TITLE
 Exclusive Gear ( Japanese and amiibo)

### ISSUE THREAD

**Issue by Onebranchyboi** [Leanny/leanny.github.io#75]
So lately in Splatoon 2 its been getting really hard to get perfect gear  so i decided to use Splathex. i was also really excited to get any kind of gear i wanted like the Emperor gear or the amiibo gear. As i was adding all of the gear to my game i couldn't find any Emperor gear amiibo gear. At first i thought it was because i was using an older version so i downloaded Splathex again but once again no gear. I looked everywhere for the gear but couldn't find it at all. I looked on Youtube to see if anyone else used Splathex there was one Youtuber ( who i'm not going to mention) who did use Splathex for the Emperor gear. There are other people who have said they have the gear but it just goes back to the default gear. I don't know if something went wrong in adding the but can you please fix it.

**Comment by 98otiss03** [comment]
I know you meant samuel bessega, Anyway for the Japanese gear you have to force your character to wear it. Or it will just disappear. It will be in your inventory but not visible, you will always have to equip the gear manually.

**Comment by Onebranchyboi** [comment]
How do I do that if I can't find the gear to begin with?

**Comment by Onebranchyboi** [comment]
How do I do that if I can't find the gear to begin with?

**Comment by Leanny** [comment]
Early versions of splathex supported it but it lead to bans for illegal gear. So we decided that most special gear is only editable when you obtain it legally in the game. If you really want to have the gear, download one of the older versions of splathex
