### ISSUE TITLE
Maybe a rank editor (Splatoon 2)

### ISSUE THREAD

**Issue by Leon7327** [Leanny/leanny.github.io#8]
Obviously I know why you wouldn't want this, because everyone is going to skip to rank x. But I'm already rank x, so maybe just for a little bit of fun to zip all the way down to C- and then trying a S+ game

**Comment by Leanny** [comment]
Rank editing is pretty dangerous, especially when you are already on X. Like, imagine you are 1st with rank X on the leaderboard and suddenly go back to C-. You will not only have an MMR that is higher than normally possible in the low ranks, but also disappear from the leaderboard. This would probably the easiest way to get banned online.
