### ISSUE TITLE
Octo Expansion Editor?

### ISSUE THREAD

**Issue by deadlyfishes** [Leanny/leanny.github.io#81]
Thanks for the great work and updates with the current release! I have a few questions about the upcoming update:

Do you have an estimate as to when the update to splathex will be released?

What kind of features will we see with the editor?

Is there a way to mod in-game things for octo expansion? (health/weapons). Would be fun to mess around with different weapons or play around in singleplayer/octo expansion with fun mods to the game

Will there at least be an option for unlocking all the items from the expansion (including the item you get from the secret boss?)

**Comment by 98otiss03** [comment]
1. They probably don't know.

2. We don't know yet but it may be similar to the octo canyon editor

3. No, only possible with romfs edits. not save edits.

4. They said no i think. idk
