### ISSUE TITLE
Improve bulk gear unlock?

### ISSUE THREAD

**Issue by Zewia** [Leanny/leanny.github.io#84]
The current bulk gear unlock does not give you any of the gears obtainable via the Octo Expansion as of now.

**Comment by Leanny** [comment]
This is intended. We might add something after vacation and finishing the OE editor though

Am 02.08.2018 01:37 schrieb Zewia <notifications@github.com>:

The current bulk gear unlock does not give you any of the gears obtainable via the Octo Expansion as of now.
