### ISSUE TITLE
Where is the Hero Headset Replica?

### ISSUE THREAD

**Issue by Squipy** [Leanny/leanny.github.io#85]
I do not have the Callie amiibo and I want the single player gear from the first game, is there a way to have that available for the next splathex patch?

**Comment by hypershadic661** [comment]
Anything involving Hero Mode (gear, weapons, etc.) requires first beating the story mode. This could be intentional like the Octo Expansion gear not being unlocked.

**Comment by Squipy** [comment]
The hero set from the first game does not require you to beat the story mode for the second game, the callie amiibo does. i have beaten the story mode and it still doesn't come up :/
