### ISSUE TITLE
having trouble opening the program?

### ISSUE THREAD

**Issue by turtlefrogg** [Leanny/leanny.github.io#86]
it pops up with an error message as soon as i open it, but it closes too fast so I can't resolve the issue myself. this issue wasn't present with older versions of the software, so i'm not sure as to what changed or what happened

**Comment by buttlet420** [comment]
This is happening for me too. After investigating, it's shoving the file into quarantine, even though I've restored it multiple times, and told my antivirus software that it's ok. The error message popping up quickly disappears but it's essentially saying something like 'missing files', like it can't open, even though everything allowing it to open is there. Idk what to do dudes.
