### ISSUE TITLE
"Failed to attempt to get the save file offset."

### ISSUE THREAD

**Issue by juuyokka** [Leanny/leanny.github.io#92]
I'm having this issue with Splathex for Splatoon 1:
I put in my Wii U's IP address, but after clicking "Connect to Gecko", I get an error stating
"Failed to attempt to get the save file offset."
followed by
"Save Pattern not found !"

What do I do?

**Comment by DiamondRain77** [comment]
Same here. I hope we get this figured out...

**Comment by Ioops4** [comment]
I actually have this issue, any link to a solution?
