### ISSUE TITLE
Suggestion: View gear ID, as well as add gear via ID

### ISSUE THREAD

**Issue by SiamesePoodleFart** [Leanny/leanny.github.io#93]
Sorry if this has already been answered previously!

**Comment by Agent-No-7** [comment]
That feature was removed. 
I’m guessing you want to add dlc gear. The game checks to see if you have a legitimate purchase. If you add the dlc gear or any gear that requires you to unlock it, the game will hide it from you. No point in adding in an item that the game auto hides from you anyways.
