### ISSUE TITLE
PSA: 4.0.0 update breaks SplatHeX and your save file possibly due to new save encryption.

### ISSUE THREAD

**Issue by 98otiss03** [Leanny/leanny.github.io#96]
Title.

**Comment by jackfusion07** [comment]
Oof.

**Comment by Leanny** [comment]
We are aware of the issue and are working on a solution. We already found a solution to this and all I need to do is to turn it into code

**Comment by iichigoz** [comment]
hello, will this be updated soon? :D

**Comment by jackfusion07** [comment]
Of course it will, just give them time; this stuff isn't easy.

**Comment by Leanny** [comment]
Done
