### ISSUE TITLE
Add missing gear

### ISSUE THREAD

**Issue by uzdo7** [Leanny/leanny.github.io#97]
Eminence Cuff
Brown FA-11 Bomber
Gray FA-11 Bomber
Green V-Neck Limited Tee
Milky Eminence Jacket
Red V-Neck Limited Tee
Milky Enperrials
SWC Logo Tee
Sennyu Goggles
Sennyu Suit
Sennyu Bon Bon Beanie
Sennyu Inksoles
Sennyu Specs
Sennyu Headphones

**Comment by Leanny** [comment]
The gear is not missing but tied to DLCs. You cannot use them without the proper DLC files anyway, so there is no need to display them when you do not have them

**Comment by uzdo7** [comment]
SWC Logo Tee is also tied to DLC?

**Comment by GLAC3D** [comment]
I don't understand, because I added some of the outfits that you listed like the milky eminence jacket, but now, when i delete it, I can't find it anymore.

**Comment by Leanny** [comment]
SWC is tied a news post, so if you obtain it outside of a certain time frame, it will flag you.
And you could a few of the items in an earlier version, but they lead to mass bans due to the missing DLC on your switch, so we removed the ability to add them if you dont own them
